PYTHON=python3
use_cuda=1
gpu_id=1
scripts=test_adder_class
model=HP_CLASS_CNN2
dataset=mnist
n_class=10
in_channels=1
save_best_model_k=4
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaschedule-20
# model_comment=lr-0.002_iden_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaschedule
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_ALMaugmentloss-1
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.41_epoch-46 # 8bit with noise
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.21_epoch-46 # 5bit with noise
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.07_epoch-50 # 3bit with noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.54_epoch-50 # 8bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.47_epoch-49 # 6bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.52_epoch-48 # 5bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.50_epoch-50 # 4bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-97.98_epoch-47 # 3bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-97.64_epoch-50 # 2bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-95.71_epoch-48 # 1bit w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-95.38_epoch-42 # 1bit
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-97.52_epoch-46 # 2bit
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.36_epoch-44 # 4bit
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_alphaloss-1_acc-98.30_epoch-46 # 6bit
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_noisecool_acc-98.33_epoch-46
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_wageinit_normscale_acc-98.33_epoch-50
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.36_epoch-46 # 8-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.33_epoch-44 # 7-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.35_epoch-46 # 6-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.15_epoch-44 # 5-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.05_epoch-46 # 4-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-96.45_epoch-47 # 3-bit basequant w/ noise abnormal??
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-97.77_epoch-45 # 3-bit basequant w/ noise new with noise cooling
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-97.10_epoch-50 # 2-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-95.19_epoch-42 # 1-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.50_epoch-47 # 8-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.38_epoch-48 # 8-bit basequant w/o noise another train
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.48_epoch-44 # 7-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.55_epoch-47 # 6-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.37_epoch-46 # 5-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.23_epoch-50 # 4-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-97.62_epoch-46 # 3-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-96.98_epoch-48 # 2-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-96.05_epoch-47 # 1-bit basequant w/o noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.59_epoch-49 # oadder 8-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.59_epoch-47 # oadder 7-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.51_epoch-48 # oadder 6-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.22_epoch-42 # oadder 5-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.26_epoch-48 # oadder 4-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-98.25_epoch-46 # oadder 3-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-97.51_epoch-44 # oadder 2-bit basequant w/ noise
# model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-95.10_epoch-48 # oadder 1-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-97.57_epoch-45 # ringonn 4-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-97.43_epoch-49 # ringonn 3-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-95.16_epoch-46 # ringonn 2-bit basequant w/ noise
model_comment=lr-0.002_relu_avgpool_phase-0_disk-0_no_calib_train_posnegw_op-2_bp-8_basequant_acc-69.99_epoch-0 # ringonn 1-bit basequant w/ noise
checkpoint_dir=focnn_mnist
full_model_comment=
hidden_list=32
kernel_list=16\ 16
pool_out_size=5
act=relu
act_thres=6
batch_size=32
img_height=28
img_width=28
out_par=2
batch_par=8
qbit=4
weight_bit=1
input_bit=1
train_mode=unaware
mode=ringonn
lr=0.002
lr_gamma=0.955
lambda_1=0 #0.1 # quantize loss
lambda_2=0 #0.05 # 0 or 0.01 # lipschitz loss / unitary loss / lagrangion loss
lambda_4=0 # weight regularization loss
lambda_5=0 # Sigma regularization loss
lambda_6=0 # Group lasso loss
lambda_7=0 # protective group lasso
lipschitz_exclude_layers=
n_thread=4
phase_1=50
phase_2=44
epoch=50
max_retrain_epoch=5
train_noise=1 # 0 or 1
strict_quantize_mask=0
gamma_noise_std=0.001 # 0.002 - 0.005
phase_noise_std=0 #0.15
disk_noise_std=0.05
voltage_decay_rate=0
weight_decay_rate=0 # 0 or 0.0002
robust_assign=0
cross_layer_lipschitz=0
conditional_update=0
train_clip_voltage=0 # 0 or 1
train_clip_upper_perc=0.75 # 0.65 - 0.95
${PYTHON} ${scripts}.py --use_cuda=${use_cuda} --gpu_id=${gpu_id} --model=${model} --dataset=${dataset} --n_class=${n_class} --in_channels=${in_channels} --full_model_comment=${full_model_comment} --model_comment=${model_comment} --batch_size=${batch_size} --img_height=${img_height} --img_width=${img_width} --quantize_bit=${qbit} --lr=${lr} --lr_gamma=${lr_gamma} --lambda_2=${lambda_2} --n_thread=${n_thread} --phase_1=${phase_1} --phase_2=${phase_2} --epoch=${epoch} --max_retrain_epoch=${max_retrain_epoch}  --train_noise=${train_noise} --gamma_noise_std=${gamma_noise_std} --phase_noise_std=${phase_noise_std} --voltage_decay_rate=${voltage_decay_rate} --strict_quantize_mask=${strict_quantize_mask} --cross_layer_lipschitz=${cross_layer_lipschitz} --conditional_update=${conditional_update} --train_clip_voltage=${train_clip_voltage} --train_clip_upper_perc=${train_clip_upper_perc} --weight_decay_rate=${weight_decay_rate} --hidden_list ${hidden_list} --kernel_list ${kernel_list} --lipschitz_exclude_layers ${lipschitz_exclude_layers} --save_best_model_k=${save_best_model_k} --checkpoint_dir=${checkpoint_dir} --lambda_4=${lambda_4} --lambda_1=${lambda_1} --lambda_5=${lambda_5} --act=${act} --act_thres=${act_thres} --lambda_6=${lambda_6} --lambda_7=${lambda_7} --weight_bit=${weight_bit} --input_bit=${input_bit} --pool_out_size=${pool_out_size} --mode=${mode} --disk_noise_std=${disk_noise_std} --train_mode=${train_mode} --out_par=${out_par} --batch_par=${batch_par} --robust_assign=${robust_assign}
