PYTHON=python3
use_cuda=1
gpu_id=0
scripts=test_adder_class
model=HP_CLASS_CNN2
dataset=mnist
n_class=10
in_channels=1
save_best_model_k=4
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_noisecool
# model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_noisecool_acc-98.33_epoch-46
model_comment=lr-0.002_relu_avgpool_phase-0.1_disk-0.05_no_calib_train_posnegw_op-2_bp-8_wageinit_normscale_acc-98.33_epoch-50
checkpoint_dir=focnn_mnist
full_model_comment=
hidden_list=32
kernel_list=16\ 16
pool_out_size=5
act=relu
act_thres=6
batch_size=8
img_height=28
img_width=28
out_par=2
batch_par=8
qbit=4
weight_bit=8
input_bit=8
train_mode=noise
mode=oconv
lr=0.002
lr_gamma=0.955
lambda_1=0 # quantize loss
lambda_2=0 #0.05 # 0 or 0.01 # lipschitz loss / unitary loss
lambda_4=0 # weight regularization loss
lambda_5=0 # Sigma regularization loss
lambda_6=0 # Group lasso loss
lambda_7=0 # protective group lasso
lipschitz_exclude_layers=
n_thread=4
phase_1=50
phase_2=44
epoch=50
max_retrain_epoch=5
train_noise=1 # 0 or 1
strict_quantize_mask=0
gamma_noise_std=0.001 # 0.002 - 0.005
phase_noise_std=0.1 #0.15
disk_noise_std=0.05
voltage_decay_rate=0
weight_decay_rate=0 # 0 or 0.0002
cross_layer_lipschitz=0
conditional_update=0
train_clip_voltage=0 # 0 or 1
train_clip_upper_perc=0.75 # 0.65 - 0.95
${PYTHON} ${scripts}.py --use_cuda=${use_cuda} --gpu_id=${gpu_id} --model=${model} --dataset=${dataset} --n_class=${n_class} --in_channels=${in_channels} --full_model_comment=${full_model_comment} --model_comment=${model_comment} --batch_size=${batch_size} --img_height=${img_height} --img_width=${img_width} --quantize_bit=${qbit} --lr=${lr} --lr_gamma=${lr_gamma} --lambda_2=${lambda_2} --n_thread=${n_thread} --phase_1=${phase_1} --phase_2=${phase_2} --epoch=${epoch} --max_retrain_epoch=${max_retrain_epoch}  --train_noise=${train_noise} --gamma_noise_std=${gamma_noise_std} --phase_noise_std=${phase_noise_std} --voltage_decay_rate=${voltage_decay_rate} --strict_quantize_mask=${strict_quantize_mask} --cross_layer_lipschitz=${cross_layer_lipschitz} --conditional_update=${conditional_update} --train_clip_voltage=${train_clip_voltage} --train_clip_upper_perc=${train_clip_upper_perc} --weight_decay_rate=${weight_decay_rate} --hidden_list ${hidden_list} --kernel_list ${kernel_list} --lipschitz_exclude_layers ${lipschitz_exclude_layers} --save_best_model_k=${save_best_model_k} --checkpoint_dir=${checkpoint_dir} --lambda_4=${lambda_4} --lambda_1=${lambda_1} --lambda_5=${lambda_5} --act=${act} --act_thres=${act_thres} --lambda_6=${lambda_6} --lambda_7=${lambda_7} --weight_bit=${weight_bit} --input_bit=${input_bit} --pool_out_size=${pool_out_size} --mode=${mode} --disk_noise_std=${disk_noise_std} --train_mode=${train_mode} --out_par=${out_par} --batch_par=${batch_par}
